### PR TITLE
Refactor: Moved IServiceProxy and IHostServiceProxy to Coral.PluginBase.

### PR DESCRIPTION
**Pull request by CaffeinatedCoder**
…d Coral.PluginHost dependency from Coral.Plugin.LastFM

#101

### CODE REVIEW

**Comment by CaffeinatedCoder** [comment]
@GOATS2K Would you mind testing it to see if everything behaves like it should?

**Comment by GOATS2K** [comment]
Sure!

**Comment by GOATS2K** [comment]
Loading a freshly built plugin fails with

```
System.MissingMethodException: 'Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.Extensions.Configuration.IConfiguration)'.'
```

On [this line](https://github.com/GOATS2K/Coral/blob/main/src/Coral.PluginHost/PluginContext.cs#L79)

**Comment by CaffeinatedCoder** [comment]
I'll have a look into it. I needed to reference a new package Microsoft.Extensions.Options.ConfigurationExtensions in Coral.Plugin.LastFM after removing the Coral.PluginHost dependency, otherwise I couldn't get it to compile in this [line](https://github.com/GOATS2K/Coral/blob/18910e12ab2e7cff16ddf3f3b211852b5dc5b761/src/Coral.Plugin.LastFM/LastFmPlugin.cs#LL27C77-L27C77)

**Comment by GOATS2K** [comment]
Ah, it works without loading the extra Microsoft.* assemblies with the plugin. Any chance we can prevent them from built with the plugin in the first place?

**Comment by CaffeinatedCoder** [comment]
Would it be suitable to reference Microsoft.Extensions.Options.ConfigurationExtensions from PluginBase project? So it would be a transitive dependency then for every plugin.

**Comment by GOATS2K** [comment]
I don't see why not. :)

**Comment by CaffeinatedCoder** [comment]
OK, fresh take :-)

**Comment by GOATS2K** [comment]
Let's see if we can prevent the PluginBase dependencies from being built with the plugin itself - we can assume that the host has them already.

**Comment by GOATS2K** [comment]
LGTM! 👍

**Pull request merged**
